name: MilkySchemUpload
version: '${project.version}'
main: fun.milkyway.milkyschemupload.MilkySchemUpload
api-version: 1.19
libraries:
  - org.apache.httpcomponents:httpclient:4.5.14
  - org.apache.httpcomponents:httpmime:4.5.14